export const TRANSLATE_MAP = {
    "Clothing": "Tøj",
    "T-SHIRT": "T-shirt",
    "SWEATSHIRT": "Sweatshirt",
    "Sweatshirt": "Sweatshirt",
    "Hoodie": "Hættetrøje",
    "HOODIE": "Hættetrøje",
    "Zipper Hoodie": "Hættetrøje med lynlås",
    "ZIPPERHOODIE": "Hættetrøje med lynlås",
    "SweatPants": "Joggingbukser",
    "SWEATPANTS": "Joggingbukser",
    "SHORTS": "Shorts",
    "Size and color": "Størrelse og farve",
    "Pressure": "Tryk",
    "T-shirt": "T-shirt",
    "Color": "Farve",
    "Red": "Rød",
    "Orange": "Orange",
    "Lime": "Lime",
    "Kit": "Kit",
    "Light blue": "Lyseblå",
    "Turquoise": "Turkis",
    "Navy": "Mørkeblå",
    "Black": "Sort",
    "White (black print)": "Hvid (sort tryk)",
    "Size": "Størrelse",
    "S": "S",
    "M": "M",
    "L": "L",
    "XL": "XL",
    "2XL": "2XL",
    "3XL": "3XL",
    "Size guide": "Størrelsesguide",
    "Samlet pris": "Samlet pris",
    "400 DKK": "400 DKK",
    "Servicegebyr på 59,00 kr. inkl.": "Servicegebyr på 59,00 kr. inkl.",
    "Godkend og betal": "Godkendt og betaling",
    "Chest Area": "Brystområde",
    "Right Chest:": "Højre bryst:",
    "Left Chest:": "Venstre bryst:",
    "Free text": "Fri tekst",
    "Enter text": "Indtast tekst",
    "Predefined flag": "Foruddefineret flag",
    "Select flag": "Vælg flag",
    "Select": "Vælg",
    "Sleeves": "Ærmer",
    "Right Sleeve:": "Højre ærme:",
    "Left Sleeve:": "Venstre ærme:",
    "Pressure Options": "Trykmuligheder",
    "Right Chest": "Højre bryst",
    "Left:": "venstre:",
    "Right:": "højre:",
    "Select a Flag": "Vælg et flag",
    "Short": "Kort",
    "Add to cart": "Læg i kurv",
    "Total Price": "Samlet pris",
    "Design Back": "Design ryg",
    "Log Out": "Log ud",
    "StudentLife": "Studenterliv",
    "Cloth Configurator": "Stofkonfigurator",
    "Selected": "Valgt ",
    "LIVE PREVIEW": "LIVE FORSIDE",
    "White": "Hvid",
    "Natural": "Naturlig",
    "Heather Grey": "Heather Grey",
    "Light Pink": "Lyserød",
    "Olive Green": "Olivengrøn",
    "Blue": "Blå",
    "Purple": "Lilla",
    "Service fee of 59.00 kr. included": "Servicegebyr på 59,00 kr. inkl.",
    "Select Type": "Vælg type",
    "Flag": "Flag",
    "Logo": "Logo",
    "Students": " Studerende",
    "Individual Configuration": "Individuel konfiguration",
    "Approve and Pay": "Godkend og betal",
    "Add Students": "Tilføj studerende",
    "Individual": "Individuel",
    "Batch (Multiple)": "Batch (flere)",
    "Student Name": "Elevens navn",
    "Enter full name": "Indtast det fulde navn",
    "Student Names (max 10)": "Elevnavne (maks. 10)",
    "+ Add another student": "+ Tilføj en anden elev",
    "Save & Continue": "Gem og fortsæt",
    "Student 1": "Elev 1",
    "Student 2": "Elev 2",
    "Student 3": "Elev 3",
    "Student 4": "Elev 4",
    "Student 5": "Elev 5",
    "Student 6": "Elev 6",
    "Student 7": "Elev 7",
    "Student 8": "Elev 8",
    "Student 9": "Elev 9",
    "Student 10": "Elev 10",
    "Currently Editing:": "Redigerer i øjeblikket: ",
    "Leg Area": "Benområde",
    "Right Leg:": "Højre ben:",
    "Left Leg:": "Venstre ben:",
    "right Chest:": "Højre bryst:",
    "Left Chest:": "Venstre bryst:",
    "right Sleeve:": "Højre ærme:",
    "Left Sleeve:": "Venstre ærme:",
    "Back Design:": "Design ryg:",
    "Finish": "Slutte",
    "Global Back Design": "Globalt rygdesign",
    "Design uploaded here will be applied to ALL students.": "Designet, der uploades her, vil blive anvendt på ALLE elever.",
    "Login": "Log ind",
    "Sign in to manage your dashboard": "Log ind for at administrere dit dashboard",
    "Log in": "Log ind",
    "© 2024 ClothConfig. All rights reserved.": "© 2024 ClothConfig. Alle rettigheder forbeholdes.",






    // Countries
    "Denmark": "Danmark",
    "United States": "USA",
    "United Kingdom": "Storbritannien",
    "Germany": "Tyskland",
    "France": "Frankrig",
    "Spain": "Spanien",
    "Italy": "Italien",
    "Netherlands": "Holland",
    "Sweden": "Sverige",
    "Norway": "Norge",
    "Finland": "Finland",
    "Poland": "Polen",
    "Japan": "Japan",
    "South Korea": "Sydkorea",
    "China": "Kina",
    "India": "Indien",
    "Brazil": "Brasilien",
    "Canada": "Canada",
    "Australia": "Australien",
    "Mexico": "Mexico",

    // Copy Design Popup
    "Copy Design?": "Kopier design?",
    "Haan, Copy Karo": "Ja, kopier",
    "Nahi, Alag Rakho": "Nej, hold adskilt",

    // Save Design Modal
    "Select Garments to Save": "Vælg beklædningsgenstande at gemme",
    "Select karein jo order mein jaane chahiye": "Vælg dem der skal med i ordren",
    "Select items to include in your order": "Vælg varer der skal med i din ordre",
    "Save Karein": "Gem",
    "Cancel": "Annuller",
    "Kam az kam ek garment select karein.": "Vælg mindst ét beklædningsstykke.",
    "Pehle koi garment configure karein.": "Konfigurer mindst ét beklædningsstykke først.",

};
