export const TRANSLATE_MAP = {
    // "Clothing": "Tøj",
    // "T-SHIRT": "T-shirt",
    // "SWEATSHIRT": "Sweatshirt",
    // "Hoodie": "Hættetrøje",
    // "HOODIE": "Hættetrøje",
    // "ZipperHoodie": "Hættetrøje med lynlås",
    // "ZIPPERHOODIE": "Hættetrøje med lynlås",
    // "SweatPants": "Joggingbukser",
    // "SWEATPANTS": "Joggingbukser",
    // "SHORTS": "Shorts",
    // "Size and color": "Størrelse og farve",
    // "Pressure": "Tryk",
    // "T-shirt": "T-shirt",
    // "Color": "Farve",
    // "Red": "Rød",
    // "Orange": "Orange",
    // "Lime": "Lime",
    // "Kit": "Kit",
    // "Light blue": "Lyseblå",
    // "Turquoise": "Turkis",
    // "Navy": "Mørkeblå",
    // "Black": "Sort",
    // "White (black print)": "Hvid (sort tryk)",
    // "Size": "Størrelse",
    // "S": "S",
    // "M": "M",
    // "L": "L",
    // "XL": "XL",
    // "2XL": "2XL",
    // "3XL": "3XL",
    // "Size guide": "Størrelsesguide",
    // "Samlet pris": "Samlet pris",
    // "400 DKK": "400 DKK",
    // "Servicegebyr på 59,00 kr. inkl.": "Servicegebyr på 59,00 kr. inkl.",
    // "Godkend og betal": "Godkendt og betaling",
    // "Chest Area": "Brystområde",
    // "Right Chest:": "Højre bryst:",
    // "Left Chest:": "Venstre bryst:",
    // "Free text": "Fri tekst",
    // "Enter text": "Indtast tekst",
    // "Predefined flag": "Foruddefineret flag",
    // "Select flag": "Vælg flag",
    // "Select": "Vælg",
    // "Sleeves": "Ærmer",
    // "Right Sleeve:": "Højre ærme:",
    // "Left Sleeve:": "Venstre ærme:",
    // "Pressure Options": "Trykmuligheder",
    // "Right Chest": "Højre bryst",
    // "Left:": "venstre:",
    // "Right:": "højre:",
    // "Select a Flag": "Vælg et flag",
    // "LIVE FORSIDE": "BO FORSIDE",
    // "Short": "Kort",
    // // Countries
    // "Denmark": "Danmark",
    // "United States": "USA",
    // "United Kingdom": "Storbritannien",
    // "Germany": "Tyskland",
    // "France": "Frankrig",
    // "Spain": "Spanien",
    // "Italy": "Italien",
    // "Netherlands": "Holland",
    // "Sweden": "Sverige",
    // "Norway": "Norge",
    // "Finland": "Finland",
    // "Poland": "Polen",
    // "Japan": "Japan",
    // "South Korea": "Sydkorea",
    // "China": "Kina",
    // "India": "Indien",
    // "Brazil": "Brasilien",
    // "Canada": "Canada",
    // "Australia": "Australien",
    // "Mexico": "Mexico",

};
